export declare const version: any;
export * from './project';
export { map, filterMap, renormalizeMap, trace } from './map';
import { exec as execFunc, run as runFunc } from './exec';
export { build } from './build';
export declare function resolve(name: string, parent?: string, env?: any, relativeFallback?: boolean): Promise<any>;
export declare function resolveSync(name: string, parent?: string, env?: any, relativeFallback?: boolean): any;
export declare const JSPM_GLOBAL_PATH: string;
export declare const exec: typeof execFunc;
export declare const run: typeof runFunc;
